// Generated by gencpp from file crazyswarm/CTBR.msg
// DO NOT EDIT!


#ifndef CRAZYSWARM_MESSAGE_CTBR_H
#define CRAZYSWARM_MESSAGE_CTBR_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <geometry_msgs/Vector3.h>

namespace crazyswarm
{
template <class ContainerAllocator>
struct CTBR_
{
  typedef CTBR_<ContainerAllocator> Type;

  CTBR_()
    : header()
    , body_rates()
    , collective_thrust(0.0)
    , thrust_raw_scale(0.0)  {
    }
  CTBR_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , body_rates(_alloc)
    , collective_thrust(0.0)
    , thrust_raw_scale(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _body_rates_type;
  _body_rates_type body_rates;

   typedef float _collective_thrust_type;
  _collective_thrust_type collective_thrust;

   typedef float _thrust_raw_scale_type;
  _thrust_raw_scale_type thrust_raw_scale;





  typedef boost::shared_ptr< ::crazyswarm::CTBR_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::crazyswarm::CTBR_<ContainerAllocator> const> ConstPtr;

}; // struct CTBR_

typedef ::crazyswarm::CTBR_<std::allocator<void> > CTBR;

typedef boost::shared_ptr< ::crazyswarm::CTBR > CTBRPtr;
typedef boost::shared_ptr< ::crazyswarm::CTBR const> CTBRConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::crazyswarm::CTBR_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::crazyswarm::CTBR_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::crazyswarm::CTBR_<ContainerAllocator1> & lhs, const ::crazyswarm::CTBR_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.body_rates == rhs.body_rates &&
    lhs.collective_thrust == rhs.collective_thrust &&
    lhs.thrust_raw_scale == rhs.thrust_raw_scale;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::crazyswarm::CTBR_<ContainerAllocator1> & lhs, const ::crazyswarm::CTBR_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace crazyswarm

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::crazyswarm::CTBR_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::crazyswarm::CTBR_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::crazyswarm::CTBR_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::crazyswarm::CTBR_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::crazyswarm::CTBR_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::crazyswarm::CTBR_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::crazyswarm::CTBR_<ContainerAllocator> >
{
  static const char* value()
  {
    return "12512d5e6e983bf9418befab5e94027f";
  }

  static const char* value(const ::crazyswarm::CTBR_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x12512d5e6e983bf9ULL;
  static const uint64_t static_value2 = 0x418befab5e94027fULL;
};

template<class ContainerAllocator>
struct DataType< ::crazyswarm::CTBR_<ContainerAllocator> >
{
  static const char* value()
  {
    return "crazyswarm/CTBR";
  }

  static const char* value(const ::crazyswarm::CTBR_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::crazyswarm::CTBR_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"geometry_msgs/Vector3 body_rates\n"
"float32 collective_thrust\n"
"# 仅作用于主机桥接层的 raw PWM 映射；0 表示兼容旧发布者并使用 1.0。\n"
"# 控制器在起飞前由冻结的电压中位数计算该值，飞行中不得逐样本改变。\n"
"float32 thrust_raw_scale\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Vector3\n"
"# This represents a vector in free space. \n"
"# It is only meant to represent a direction. Therefore, it does not\n"
"# make sense to apply a translation to it (e.g., when applying a \n"
"# generic rigid transformation to a Vector3, tf2 will only apply the\n"
"# rotation). If you want your data to be translatable too, use the\n"
"# geometry_msgs/Point message instead.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::crazyswarm::CTBR_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::crazyswarm::CTBR_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.body_rates);
      stream.next(m.collective_thrust);
      stream.next(m.thrust_raw_scale);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CTBR_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::crazyswarm::CTBR_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::crazyswarm::CTBR_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "header: ";
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "body_rates: ";
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.body_rates);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "collective_thrust: ";
    Printer<float>::stream(s, indent + "  ", v.collective_thrust);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "thrust_raw_scale: ";
    Printer<float>::stream(s, indent + "  ", v.thrust_raw_scale);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CRAZYSWARM_MESSAGE_CTBR_H
